<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        /* dompdf-safe report export: tables only, no flexbox/transforms. */
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 8.5px; color: #1a1a1a; }
        .masthead { border-bottom: 2px solid #1b2a4a; padding-bottom: 6px; margin-bottom: 10px; }
        .masthead h1 { font-size: 13px; margin: 0 0 2px; color: #1b2a4a; }
        .masthead .sub { font-size: 9px; color: #444; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #999; padding: 3px 5px; text-align: left; vertical-align: top; word-wrap: break-word; }
        th { background: #eef1f5; font-weight: bold; font-size: 8px; text-transform: uppercase; }
        tr.totals td { font-weight: bold; background: #eef1f5; border-top: 2px solid #1b2a4a; }
        .num { text-align: right; font-variant-numeric: tabular-nums; }
        .foot { margin-top: 14px; font-size: 7.5px; color: #666; border-top: 1px solid #ccc; padding-top: 6px; }
        .empty { text-align: center; color: #666; padding: 20px 0; }
    </style>
</head>
<body>
    @include('partials.letterhead', ['mb' => 14, 'subtitle' => 'Department of Information and Communications Technology · Regional Office 2'])

    <div class="masthead">
        <h1>{{ $title }}</h1>
        <div class="sub">{{ $subtitle ?? 'Official HRIS report' }} · Generated {{ now()->format('F j, Y · g:i A') }} by {{ auth()->user()?->name ?? '—' }}</div>
    </div>

    @if ($rows->isEmpty())
        <div class="empty">No records match the current filters.</div>
    @else
        <table>
            <thead>
                <tr>
                    @foreach ($headers as $header)
                        <th>{{ $header }}</th>
                    @endforeach
                </tr>
            </thead>
            <tbody>
                @foreach ($rows as $row)
                    <tr>
                        @foreach ($row as $cell)
                            <td class="{{ is_numeric($cell) ? 'num' : '' }}">{{ $cell }}</td>
                        @endforeach
                    </tr>
                @endforeach
                @if (! empty($totals))
                    <tr class="totals">
                        @foreach ($totals as $cell)
                            <td>{{ $cell }}</td>
                        @endforeach
                    </tr>
                @endif
            </tbody>
        </table>
    @endif

    <div class="foot">
        Certified true and correct. Generated by the DICT RO2 Employee Management System · This report is unofficial until signed.
    </div>
</body>
</html>
